# Generated by Django 4.2 on 2023-04-26 16:33

import cloud.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                (
                    "image",
                    models.ImageField(upload_to=cloud.models.user_directory_path),
                ),
                (
                    "image_caption",
                    models.CharField(default="photo by demo", max_length=100),
                ),
                ("publish", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
